### ISSUE TITLE
Valid API Key returning Forbidden

### ISSUE THREAD

**Issue by LucasMcManus** [meraki-analytics/orianna#100]
Title says it all, I got a brand new API key and it did not work, in fact none of the API keys I have had have worked, at least when I set them programmatically, Thanks for the help

**Comment by robrua** [comment]
Hey, what version of Orianna are you using?

My first guess as to why something like this might happen is loading a config after setting your API key programmatically? If that's happening, the config loading will overwrite the programmatically set API key for the config.

Otherwise, would you mind sending an example of how you're setting your Riot API key and your Orianna configuration?

**Comment by LucasMcManus** [comment]
Hi Rob, than you for replying so quickly,
I am using version SNAPSHOT 3.1.0
Attached is a screenshot of one way I am using Orianna.

Thank you for the help,
Lucas

**Comment by robrua** [comment]
Hey - unfortunately the attachment doesn't come through when replying via email to GitHub. However, I suspect your issue may be trying to use an endpoint that has been removed by Riot lately. A lot has changed with the API recently, and I'd recommend upgrading to version 4.0.0-SNAPSHOT rather than 3.1.0-SNAPSHOT.

**Comment by LucasMcManus** [comment]
Wow, thank you!
That worked, upgrading frmo the 3.1.0 to 4.0.0 snapshot fixed everything,
thanks for the quick responses and Ill definitely be using this for my
application now :)

**Comment by robrua** [comment]
Nice! Glad to be of help!
