### ISSUE TITLE
I always login LOL with QQ，how can I get the roit API Key?

### ISSUE THREAD

**Issue by GongShengyue** [meraki-analytics/orianna#112]

**Comment by robrua** [comment]
Hey,

The Chinese LoL accounts are managed separately from Riot, so I'm not sure if you can get credentials that work with developer.riotgames.com from that account. I'm asking around to see if there's a way, but a good workaround would be just creating an account on one of the western servers (e.g. na.leagueoflegends.com or euw.leagueoflegends.com) and using those credentials to access the API.

I will note, if you weren't already aware, that the API only has data for Brazil, Europe, Japan, Korea, Latin America, North America, Oceania, Turkey, and Russia. Once again, because the accounts are managed separately for China that data isn't available in the API.
