### ISSUE TITLE
How I can get the timeline of a match?

### ISSUE THREAD

**Issue by MinCha** [meraki-analytics/orianna#94]
Dear developers,
As a title, How I can get the timeline of a match?
I could not find out a method to call a URL as "/lol/match/v3/timelines/by-match/{matchId}"

**Comment by jjmaldonis** [comment]
You can use `a_match.getTimeline()`.

**Comment by MinCha** [comment]
@jjmaldonis That`s a just Timeline, not MatchTimeline. How can I use MatchTimeline?

**Comment by robrua** [comment]
Timeline is the `core`-level user-facing type that should be used to access information from "/lol/match/v3/timelines/by-match/{matchId}". MatchTimeline is a data container used internally to support Timeline. If you're using the `core` types in the rest of your code with Orianna, you definitely want Timeline rather than MatchTimeline.

You can also get a Timeline using Timeline.withId(matchId).get() in addition to match.getTimeline().

If you're sure you want to use the raw `dto`-level data containers that are used internally instead of the `core` Orianna API, there's no convenient user-facing API for getting that data. Let me know if that's the case and I can give you some details on how you would do that.
